---
- name: Deploy Elasticsearch, kibana and transform_password password
  hosts: elastic
  become: true
  roles:
    - elastic
    - kibana
    - transform_password

- name: Deploy Logstash
  hosts: logstash
  become: true
  roles:
    - logstash

- name: Deploy Filebeat
  hosts: filebeat
  become: true
  roles:
    - filebeat

  post_tasks:
    - name: Elasticsearch User And Password
      debug:
        msg: "User : Elastic, Password: {{ elastic_password }}"
      delegate_to: ansible
