--- 
    - name: Overwrite the password.txt file on the control server
      local_action:
        module: copy
        content: "{{ elastic_password }}"
        dest: "/etc/ansible/roles/logstash/templates/password.txt"
        mode: '0600'
      delegate_to: ansible

    - name: Fetch key files from remote host
      fetch:
        src: /etc/elasticsearch/certs/ca.key.pem
        dest: /etc/ansible/roles/logstash/templates/
        flat: yes

    - name: Fetch certificate files from remote host
      fetch:
        src: /etc/elasticsearch/certs/ca.crt.pem
        dest: /etc/ansible/roles/logstash/templates/
        flat: yes